Added two classes
Monsotya/Sudoku-WPF pull request #1
Opened 2021-11-20 11:45 UTC by Monsotya

2021-11-20 11:50 UTC, Yehukh commented on Sudoku.Application/ModifySudokuMethods.cs
> +    public class ModifySudokuMethods
Consider changing accessor to internal

2021-11-20 11:51 UTC, Yehukh commented on Sudoku.Application/ModifySudokuMethods.cs
> +    public class ModifySudokuMethods
Also, I would like to rename the class name. Not self-describing :)

2021-11-20 11:52 UTC, Yehukh requested changes
Change the ModifySudokuMethods.cs

2021-11-24 08:09 UTC, Monsotya commented
I need to make more changes

2021-11-26 19:32 UTC, Yehukh requested changes

2021-11-26 19:32 UTC, Yehukh commented on Sudoku.Application/MixSudoku.cs
> +		public void SwapRows(int[][] matrix)
remove spaces in this function :)

2021-11-26 19:32 UTC, Yehukh commented on Sudoku.Application/CreateSudoku.cs
> +        public void DeleteCells()
how many cells will be deleted. Should we specify this number as a parameter( for example defined by complexity)

2021-11-26 19:35 UTC, Yehukh commented on Sudoku.Application/MixSudoku.cs
> +        public void Transpose(int[][] matrix)
Why we aren't returning this matrix back?

2021-11-27 13:06 UTC, Yehukh approved these changes

2021-11-27 13:07 UTC, merged